#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: assure ufw installed
  apt: pkg=ufw state=present

- name: enable ufw service at boot
  service: name=ufw enabled=True

- name: set ufw default forward policy to deny
  lineinfile:
    dest=/etc/default/ufw
    regexp='^DEFAULT_FORWARD_POLICY='
    line='DEFAULT_FORWARD_POLICY="ACCEPT"'
    state=present
  when: iptables_masquerade
  notify:
    - restart ufw

- name: set ufw default forward policy to accept
  lineinfile:
    dest=/etc/default/ufw
    regexp='^DEFAULT_FORWARD_POLICY='
    line='DEFAULT_FORWARD_POLICY="DENY"'
    state=present
  when: not iptables_masquerade
  notify:
    - restart ufw

- name: set default ufw policy to deny
  ufw: state=enabled policy=deny
  when: iptables_masquerade
  notify:
    - restart ufw

- name: set default ufw policy to allow
  ufw: state=enabled policy=allow
  when: not iptables_masquerade
  notify:
    - restart ufw

- name: set forwarding rules on if necessary
  lineinfile:
    dest=/etc/ufw/sysctl.conf
    line="net/ipv4/ip_forward=1"
    state=present
  when: iptables_masquerade
  notify:
    - restart ufw

- name: set forwarding rules off if necessary
  lineinfile:
    dest=/etc/ufw/sysctl.conf
    line="net/ipv4/ip_forward=1"
    state=absent
  when: not iptables_masquerade
  notify:
    - restart ufw

- name: set sysctl forwarding rules off
  lineinfile:
    dest=/etc/ufw/sysctl.conf
    line="net/ipv4/ip_forward=1"
    state=absent
  when: not iptables_masquerade
  notify:
    - restart ufw

- name: configure iptables masquerading
  template: src=Debian/ufw/before.rules.j2 dest=/etc/ufw/before.rules mode=0644
  when: iptables_masquerade
  notify:
    - restart ufw

- name: allow port forwards in
  ufw:
    route: yes
    rule: allow
    direction: in
    interface: "{{ item.interface }}"
    dest: "{{ item.fwd_address }}"
    to_port: "{{ item.dport | int }}"
    proto: "{{ item.proto }}"
  with_items: "{{ iptables_forwards }}"
  when: iptables_masquerade and iptables_forwards is defined
  notify:
    - restart ufw

- name: enable ssh (always)
  ufw: rule=allow name=OpenSSH
  notify:
    - restart ufw

- name: Allow all access from trusted networks to this host
  ufw: rule=allow src={{ item }}
  with_items: "{{ iptables_allowed_networks }}"
  when: iptables_masquerade and iptables_allowed_networks is defined
  notify:
    - restart ufw

- name: enable inbound ports
  ufw: rule=allow proto={{ item.proto }} port={{ item.port }}
  with_items: "{{ iptables_enable_ports }}"
  when: iptables_masquerade and iptables_enable_ports is defined
  notify:
    - restart ufw

- name: setup kernel tracking
  lineinfile:
    dest: /etc/default/ufw
    regexp: '^IPT_MODULES='
    line: 'IPT_MODULES="{{ iptables_kernel_modules }}"'
    state: present
  notify:
    - restart ufw

- name: enable masquerading
  service: name=ufw state=started enabled=yes
  when: iptables_masquerade

- name: disable masquerading
  service: name=ufw state=stopped enabled=no
  when: not iptables_masquerade
  notify:
    - stop ufw
